# Generated by Django 4.1.5 on 2023-02-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_userachievement_fountain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
    ]
