# Generated by Django 4.1.5 on 2023-03-14 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_filledbottle_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('cost', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='static/shop_items/')),
            ],
        ),
        migrations.AlterField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/buildings/'),
        ),
        migrations.AlterField(
            model_name='buildingfloor',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/floors/'),
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.shopitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
