# Generated by Django 4.1.7 on 2023-03-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_shopitem_alter_building_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='points_reward',
        ),
        migrations.AddField(
            model_name='achievement',
            name='item_reward',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.shopitem'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='availableForPurchase',
            field=models.BooleanField(default=True),
        ),
    ]
