# Generated by Django 4.1.5 on 2023-02-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_rename_question_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='user_points_in_building',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
