# Generated by Django 4.1.7 on 2023-02-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_leaderboard_user_points_in_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bottles',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
