# Generated by Django 4.1.7 on 2023-03-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_achievement_points_reward_and_more'),
        ('database', '0005_userfriend'),
    ]

    operations = [
    ]
