# Generated by Django 4.1.7 on 2023-02-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_user_bottles'),
        ('database', '0006_user_email_alter_user_username'),
    ]

    operations = [
    ]
