# Generated by Django 4.1.7 on 2023-02-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_merge_20230224_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
